const points = [
    "It is certain",
    "It is decidedly so",
    "Without a doubt",
    "Yes definitely",
    "As I see it, yes",
    "Most likely",
    "Outlook good",
    "Signs point to yes",
    "Reply hazy, try again",
    "Ask again later",	
    "Better not tell you now",
    "Cannot predict now",
    "Concentrate and ask again",
    "Very doubtful",
    "Outlook not so good",
    "My sources say no",
    "My reply is no",
    "Not today"
];
